# Using deep learning to predict tennis games

I'm going to test deep learning on tennis predictions. In this notebook, I'll be analyzing some of the data I collected, creating some more data and finally analyzing which data is important.

## Importing data:
I'm starting off by using 2017 tennis data from http://www.tennis-data.co.uk/alldata.php
After working with this data, I'll add all data from 2001 up to 2018 to train the model.

In [4]:
import xlrd
import pandas as pd
import numpy as np
import datetime
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.preprocessing.text import one_hot
import os, glob

c:\users\kalera\appdata\local\continuum\anaconda3\envs\gpu\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.

In [5]:
data_path = "data/Tennis/*.xlsx"
data = []

for file in glob.glob(data_path):
    data_book = xlrd.open_workbook(file)

    assert data_book.nsheets == 1  # Check that the file only has one data sheet 

    data_sheet = data_book.sheet_by_index(0)
    num_rows = data_sheet.nrows
    #data = [data_sheet.row_values(i+1) for i in range(num_rows-1)]
    data += [data_sheet.row_values(i+1) for i in range(num_rows-1)]

"""for i in range(len(data)-1):
    data[i+1][3] = xlrd.xldate.xldate_as_datetime(float(data[i+1][3]), 0)"""

'for i in range(len(data)-1):\n    data[i+1][3] = xlrd.xldate.xldate_as_datetime(float(data[i+1][3]), 0)'

In [9]:
print(len(data))

13120

In [11]:
pd.set_option("display.max_columns", None)
pd.DataFrame(data=data).head(1)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41
0,1.0,Brisbane,Brisbane International,41274.0,ATP250,Outdoor,Hard,1st Round,3.0,Mayer F.,Giraldo S.,28,57,1215,778,6,4,6,4,,,,,,,2,0,Completed,1.36,3,1.45,2.65,1.44,2.62,1.47,2.85,1.44,2.63,1.47,3.2,1.42,2.78

In [12]:
players = np.unique([data[i][9:10] for i in range(len(data))])
print(len(players))
print(players)

355
['Ahouda A.' 'Albot R.' 'Almagro N.' 'Altmaier D.' 'Alund M.'
 'Amritraj P.' 'Anderson K.' 'Andreozzi G.' 'Andujar P.' 'Arguello F.'
 'Arnaboldi A.' 'Bachinger M.' 'Baghdatis M.' 'Bagnis F.' 'Bai Y.'
 'Baker B.' 'Balazs A.' 'Barton M.' 'Basic M.' 'Basilashvili N.'
 'Bautista Agut R.' 'Bautista R.' 'Becker B.' 'Bedene A.' 'Bellucci T.'
 'Bemelmans R.' 'Benneteau J.' 'Berankis R.' 'Berdych T.' 'Berlocq C.'
 'Berrer M.' 'Bhambri Y.' 'Blake J.' 'Bogomolov A.' 'Bolelli S.'
 'Bonzi B.' 'Bourgue M.' 'Brands D.' 'Broady L.' 'Brown D.'
 'Brugues-Davi A.' 'Bublik A.' 'Cacic N.' 'Capdeville P.'
 'Carballes Baena R.' 'Carreno Busta P.' 'Carreno-Busta P.'
 'Cecchinato M.' 'Cervantes I.' 'Chardy J.' 'Chiudinelli M.' 'Chung H.'
 'Cilic M.' 'Cipolla F.' 'Copil M.' 'Coric B.' 'Cuevas P.' 'Dancevic F.'
 'Daniel T.' 'Darcis S.' 'Davydenko N.' 'Davydenko P.' 'De Bakker T.'
 'De Greef A.' 'De Minaur A.' 'De Schepper K.' 'Del Potro J. M.'
 'Del Potro J.M.' 'Delbonis F.' 'Delic M.' 'Demoliner M.' 'Devvarman S.'
 'Diez S.' 'Dimitrov G.' 'Djere L.' 'Djokovic N.' 'Dodig I.'
 'Dolgopolov O.' 'Domingues J.' 'Donaldson J.' 'Donati M.' 'Donskoy E.'
 'Duckworth J.' 'Dutra Silva R.' 'Dzumhur D.' 'Ebden M.' 'Edmund K.'
 'El Amrani R.' 'Elias G.' 'Escobedo E.' 'Estrella Burgos V.' 'Eubanks C.'
 'Evans D.' 'Fabbiano T.' 'Falla A.' 'Federer R.' 'Ferrer D.' 'Fish M.'
 'Fognini F.' 'Fratangelo B.' 'Fritz T.' 'Fucsovics M.' 'Gabashvili T.'
 'Gaio F.' 'Galan D.E.' 'Garcia-Lopez G.' 'Garin C.' 'Gasquet R.'
 'Ghem A.' 'Giannessi A.' 'Gicquel M.' 'Gimeno-Traver D.' 'Ginepri R.'
 'Giraldo S.' 'Goffin D.' 'Gojowczyk P.' 'Golubev A.' 'Gombos N.'
 'Gomez A.' 'Gomez E.' 'Gonzalez A.' 'Gonzalez M.' 'Granollers M.'
 'Groth S.' 'Guccione C.' 'Gulbis E.' 'Haas T.' 'Haase R.'
 'Haider-Maurer A.' 'Hajek J.' 'Halys Q.' 'Hanescu V.' 'Hanfmann Y.'
 'Harrison C.' 'Harrison R.' 'Hemery C.' 'Herbert P.H' 'Herbert P.H.'
 'Hernych J.' 'Hewitt L.' 'Huta Galung J.' 'Ilhan M.' 'Isner J.'
 'Istomin D.' 'Ito T.' 'Janowicz J.' 'Jarry N.' 'Jasika O.' 'Jaziri M.'
 'Johansson J.' 'Johnson S.' 'Jones G.' 'Kamke T.' 'Karatsev A.'
 'Karlovic I.' 'Kavcic B.' 'Khachanov K.' 'Kicker N.' 'King D.' 'King E.'
 'Klahn B.' 'Klein B.' 'Klizan M.' 'Kohlschreiber P.' 'Kohlschreiber P..'
 'Kokkinakis T.' 'Korolev E.' 'Kovalik J.' 'Kozlov S.' 'Krajicek A.'
 'Krajinovic F.' 'Kravchuk K.' 'Krueger M.' 'Kubler J.' 'Kubot L.'
 'Kudla D.' 'Kudryavtsev A.' 'Kukushkin M.' 'Kuznetsov Al.'
 'Kuznetsov An.' 'Kyrgios N.' 'Laaksonen H.' 'Lacko L.' 'Lajovic D.'
 'Lamasine T.' 'Langer N.' 'Lapentti G.' 'Levine J.' 'Lindell C.'
 'Llodra M.' 'Lopez F.' 'Lorenzi P.' 'Lu Y.H.' 'Machado R.' 'Maden Y.'
 'Mahut N.' 'Malisse X.' 'Mannarino A.' 'Marchenko I.' 'Marti Y.'
 'Martin A.' 'Mathieu P.H.' 'Matosevic M.' 'Mayer F.' 'Mayer L.'
 'Mecir M.' 'Medvedev D.' 'Mektic N.' 'Melzer G.' 'Melzer J.'
 'Menendez-Maceiras A.' 'Mertl J.' 'Michon A.' 'Millman J.' 'Millot V.'
 'Milojevic N.' 'Mina G.' 'Monaco J.' 'Monfils G.' 'Montanes A.'
 'Monteiro T.' 'Moriya H.' 'Muller G.' 'Munar J.' 'Munoz De La Nava D.'
 'Munoz-De La Nava D.' 'Murray A.' 'Nadal R.' 'Nalbandian D.'
 'Napolitano S.' 'Nedovyesov A.' 'Nieminen J.' 'Nishikori K.'
 'Nishioka Y.' 'Norrie C.' 'Novak D.' 'Novikov D.' 'Odesnik W.' 'Ofner S.'
 'Olaso G.' 'Olivetti A.' 'Olivo R.' 'Opelka R.' 'Ouahab L.' 'Paire B.'
 'Paul T.' 'Pavic A.' 'Pavic M.' 'Pavlasek A.' 'Peliwo F.' 'Pella G.'
 'Petzschner P.' 'Phau B.' 'Polansky P.' 'Pospisil J.' 'Pospisil V.'
 'Pouille L.' 'Przysiezny M.' 'Puetz T.' 'Querrey S.' 'Quinzi G.' 'Ram R.'
 'Ramanathan R.' 'Ramirez-Hidalgo R.' 'Ramos A.' 'Ramos-Vinolas A.'
 'Raonic M.' 'Reister J.' 'Reynolds B.' 'Riba P.' 'Robert S.' 'Robredo T.'
 'Rochus O.' 'Roger-Vasselin E.' 'Rola B.' 'Rosol L.' 'Rubin N.'
 'Rublev A.' 'Rufin G.' 'Russell M.' 'Ruud C.' 'Safwat M.' 'Sakharov G.'
 'Sandgren T.' 'Santillan A.' 'Sarkissian A.' 'Satral J.' 'Saville L.'
 'Schwartzman D.' 'Sela D.' 'Seppi A.' 'Shapovalov D.' 'Sidorenko A.'
 'Sijsling I.' 'Silva F.F.' 'Simon G.' 'Skugor F.' 'Smith J.P.'
 'Smyczek T.' 'Sock J.' 'Soderlund C.' 'Soeda G.' 'Sorensen L.' 'Sousa J.'
 'Sousa P.' 'Souza J.' 'Stakhovsky S.' 'Starace P.' 'Stebe C-M.'
 'Stebe C.M.' 'Stepanek R.' 'Struff J.L.' 'Sugita Y.' 'Thiem D.'
 'Thompson J.' 'Tiafoe F.' 'Tipsarevic J.' 'Tomic B.' 'Travaglia S.'
 'Trinker B.' 'Troicki V.' 'Trungelliti M.' 'Tsitsipas S.' 'Tsonga J.W.'
 'Tursunov D.' 'Uchiyama Y.' 'Ungur A.' 'Vanni L.' 'Venus M.'
 'Verdasco F.' 'Vesely J.' 'Viola M.' 'Volandri F.' 'Wang C.' 'Wang J.'
 'Ward J.' 'Wawrinka S.' 'Weintraub A.' 'Wessels L.' 'Whittington A.'
 'Williams R.' 'Willis M.' 'Wu D.' 'Ymer E.' 'Ymer M.' 'Young D.'
 'Youzhny M.' 'Zeballos H.' 'Zekic M.' 'Zemlja G.' 'Zhang Ze' 'Zhang Zh.'
 'Zopp J.' 'Zverev A.' 'Zverev M.']

In [13]:
player_games = []
for player in players:
    d = [data[i]  for i in range(len(data)) if ((data[i][9] == player) | (data[i][10] == player))]
    player_games.append([player, d])

for pg in player_games:
    print("Player {} has played {} matches".format(pg[0], len(pg[1])))

Player Ahouda A. has played 3 matches
Player Albot R. has played 49 matches
Player Almagro N. has played 194 matches
Player Altmaier D. has played 5 matches
Player Alund M. has played 17 matches
Player Amritraj P. has played 4 matches
Player Anderson K. has played 284 matches
Player Andreozzi G. has played 6 matches
Player Andujar P. has played 140 matches
Player Arguello F. has played 16 matches
Player Arnaboldi A. has played 10 matches
Player Bachinger M. has played 21 matches
Player Baghdatis M. has played 182 matches
Player Bagnis F. has played 43 matches
Player Bai Y. has played 4 matches
Player Baker B. has played 19 matches
Player Balazs A. has played 2 matches
Player Barton M. has played 8 matches
Player Basic M. has played 15 matches
Player Basilashvili N. has played 75 matches
Player Bautista Agut R. has played 110 matches
Player Bautista R. has played 209 matches
Player Becker B. has played 143 matches
Player Bedene A. has played 145 matches
Player Bellucci T. has played 176 matches
Player Bemelmans R. has played 33 matches
Player Benneteau J. has played 152 matches
Player Berankis R. has played 105 matches
Player Berdych T. has played 340 matches
Player Berlocq C. has played 141 matches
Player Berrer M. has played 43 matches
Player Bhambri Y. has played 16 matches
Player Blake J. has played 23 matches
Player Bogomolov A. has played 22 matches
Player Bolelli S. has played 97 matches
Player Bonzi B. has played 2 matches
Player Bourgue M. has played 4 matches
Player Brands D. has played 73 matches
Player Broady L. has played 8 matches
Player Brown D. has played 113 matches
Player Brugues-Davi A. has played 3 matches
Player Bublik A. has played 10 matches
Player Cacic N. has played 2 matches
Player Capdeville P. has played 2 matches
Player Carballes Baena R. has played 30 matches
Player Carreno Busta P. has played 111 matches
Player Carreno-Busta P. has played 107 matches
Player Cecchinato M. has played 26 matches
Player Cervantes I. has played 43 matches
Player Chardy J. has played 237 matches
Player Chiudinelli M. has played 22 matches
Player Chung H. has played 77 matches
Player Cilic M. has played 290 matches
Player Cipolla F. has played 11 matches
Player Copil M. has played 54 matches
Player Coric B. has played 150 matches
Player Cuevas P. has played 184 matches
Player Dancevic F. has played 24 matches
Player Daniel T. has played 46 matches
Player Darcis S. has played 71 matches
Player Davydenko N. has played 62 matches
Player Davydenko P. has played 2 matches
Player De Bakker T. has played 54 matches
Player De Greef A. has played 8 matches
Player De Minaur A. has played 7 matches
Player De Schepper K. has played 79 matches
Player Del Potro J. M. has played 3 matches
Player Del Potro J.M. has played 169 matches
Player Delbonis F. has played 167 matches
Player Delic M. has played 9 matches
Player Demoliner M. has played 2 matches
Player Devvarman S. has played 39 matches
Player Diez S. has played 6 matches
Player Dimitrov G. has played 313 matches
Player Djere L. has played 14 matches
Player Djokovic N. has played 348 matches
Player Dodig I. has played 141 matches
Player Dolgopolov O. has played 230 matches
Player Domingues J. has played 2 matches
Player Donaldson J. has played 74 matches
Player Donati M. has played 2 matches
Player Donskoy E. has played 95 matches
Player Duckworth J. has played 51 matches
Player Dutra Silva R. has played 51 matches
Player Dzumhur D. has played 120 matches
Player Ebden M. has played 68 matches
Player Edmund K. has played 108 matches
Player El Amrani R. has played 3 matches
Player Elias G. has played 55 matches
Player Escobedo E. has played 30 matches
Player Estrella Burgos V. has played 99 matches
Player Eubanks C. has played 7 matches
Player Evans D. has played 54 matches
Player Fabbiano T. has played 34 matches
Player Falla A. has played 81 matches
Player Federer R. has played 300 matches
Player Ferrer D. has played 336 matches
Player Fish M. has played 15 matches
Player Fognini F. has played 284 matches
Player Fratangelo B. has played 36 matches
Player Fritz T. has played 65 matches
Player Fucsovics M. has played 20 matches
Player Gabashvili T. has played 119 matches
Player Gaio F. has played 6 matches
Player Galan D.E. has played 2 matches
Player Garcia-Lopez G. has played 222 matches
Player Garin C. has played 6 matches
Player Gasquet R. has played 275 matches
Player Ghem A. has played 4 matches
Player Giannessi A. has played 17 matches
Player Gicquel M. has played 8 matches
Player Gimeno-Traver D. has played 122 matches
Player Ginepri R. has played 15 matches
Player Giraldo S. has played 174 matches
Player Goffin D. has played 271 matches
Player Gojowczyk P. has played 47 matches
Player Golubev A. has played 51 matches
Player Gombos N. has played 17 matches
Player Gomez A. has played 2 matches
Player Gomez E. has played 4 matches
Player Gonzalez A. has played 46 matches
Player Gonzalez M. has played 24 matches
Player Granollers M. has played 200 matches
Player Groth S. has played 88 matches
Player Guccione C. has played 3 matches
Player Gulbis E. has played 182 matches
Player Haas T. has played 127 matches
Player Haase R. has played 213 matches
Player Haider-Maurer A. has played 68 matches
Player Hajek J. has played 26 matches
Player Halys Q. has played 19 matches
Player Hanescu V. has played 71 matches
Player Hanfmann Y. has played 11 matches
Player Harrison C. has played 5 matches
Player Harrison R. has played 128 matches
Player Hemery C. has played 4 matches
Player Herbert P.H has played 16 matches
Player Herbert P.H. has played 63 matches
Player Hernych J. has played 17 matches
Player Hewitt L. has played 88 matches
Player Huta Galung J. has played 11 matches
Player Ilhan M. has played 34 matches
Player Isner J. has played 293 matches
Player Istomin D. has played 211 matches
Player Ito T. has played 47 matches
Player Janowicz J. has played 145 matches
Player Jarry N. has played 7 matches
Player Jasika O. has played 4 matches
Player Jaziri M. has played 123 matches
Player Johansson J. has played 2 matches
Player Johnson S. has played 224 matches
Player Jones G. has played 2 matches
Player Kamke T. has played 83 matches
Player Karatsev A. has played 7 matches
Player Karlovic I. has played 244 matches
Player Kavcic B. has played 51 matches
Player Khachanov K. has played 80 matches
Player Kicker N. has played 26 matches
Player King D. has played 8 matches
Player King E. has played 3 matches
Player Klahn B. has played 17 matches
Player Klein B. has played 7 matches
Player Klizan M. has played 180 matches
Player Kohlschreiber P. has played 272 matches
Player Kohlschreiber P.. has played 2 matches
Player Kokkinakis T. has played 49 matches
Player Korolev E. has played 4 matches
Player Kovalik J. has played 18 matches
Player Kozlov S. has played 20 matches
Player Krajicek A. has played 34 matches
Player Krajinovic F. has played 37 matches
Player Kravchuk K. has played 22 matches
Player Krueger M. has played 5 matches
Player Kubler J. has played 2 matches
Player Kubot L. has played 47 matches
Player Kudla D. has played 75 matches
Player Kudryavtsev A. has played 8 matches
Player Kukushkin M. has played 144 matches
Player Kuznetsov Al. has played 19 matches
Player Kuznetsov An. has played 146 matches
Player Kyrgios N. has played 159 matches
Player Laaksonen H. has played 38 matches
Player Lacko L. has played 97 matches
Player Lajovic D. has played 148 matches
Player Lamasine T. has played 5 matches
Player Langer N. has played 3 matches
Player Lapentti G. has played 4 matches
Player Levine J. has played 20 matches
Player Lindell C. has played 7 matches
Player Llodra M. has played 37 matches
Player Lopez F. has played 275 matches
Player Lorenzi P. has played 189 matches
Player Lu Y.H. has played 158 matches
Player Machado R. has played 5 matches
Player Maden Y. has played 3 matches
Player Mahut N. has played 158 matches
Player Malisse X. has played 32 matches
Player Mannarino A. has played 236 matches
Player Marchenko I. has played 61 matches
Player Marti Y. has played 5 matches
Player Martin A. has played 15 matches
Player Mathieu P.H. has played 120 matches
Player Matosevic M. has played 105 matches
Player Mayer F. has played 127 matches
Player Mayer L. has played 166 matches
Player Mecir M. has played 4 matches
Player Medvedev D. has played 55 matches
Player Mektic N. has played 7 matches
Player Melzer G. has played 35 matches
Player Melzer J. has played 109 matches
Player Menendez-Maceiras A. has played 13 matches
Player Mertl J. has played 2 matches
Player Michon A. has played 2 matches
Player Millman J. has played 66 matches
Player Millot V. has played 20 matches
Player Milojevic N. has played 2 matches
Player Mina G. has played 3 matches
Player Monaco J. has played 156 matches
Player Monfils G. has played 244 matches
Player Montanes A. has played 98 matches
Player Monteiro T. has played 45 matches
Player Moriya H. has played 7 matches
Player Muller G. has played 181 matches
Player Munar J. has played 4 matches
Player Munoz De La Nava D. has played 8 matches
Player Munoz-De La Nava D. has played 16 matches
Player Murray A. has played 318 matches
Player Nadal R. has played 350 matches
Player Nalbandian D. has played 11 matches
Player Napolitano S. has played 3 matches
Player Nedovyesov A. has played 23 matches
Player Nieminen J. has played 133 matches
Player Nishikori K. has played 304 matches
Player Nishioka Y. has played 45 matches
Player Norrie C. has played 6 matches
Player Novak D. has played 7 matches
Player Novikov D. has played 14 matches
Player Odesnik W. has played 10 matches
Player Ofner S. has played 8 matches
Player Olaso G. has played 3 matches
Player Olivetti A. has played 10 matches
Player Olivo R. has played 47 matches
Player Opelka R. has played 19 matches
Player Ouahab L. has played 5 matches
Player Paire B. has played 248 matches
Player Paul T. has played 16 matches
Player Pavic A. has played 13 matches
Player Pavic M. has played 8 matches
Player Pavlasek A. has played 12 matches
Player Peliwo F. has played 6 matches
Player Pella G. has played 98 matches
Player Petzschner P. has played 11 matches
Player Phau B. has played 13 matches
Player Polansky P. has played 18 matches
Player Pospisil J. has played 3 matches
Player Pospisil V. has played 171 matches
Player Pouille L. has played 145 matches
Player Przysiezny M. has played 46 matches
Player Puetz T. has played 3 matches
Player Querrey S. has played 242 matches
Player Quinzi G. has played 2 matches
Player Ram R. has played 73 matches
Player Ramanathan R. has played 15 matches
Player Ramirez-Hidalgo R. has played 11 matches
Player Ramos A. has played 70 matches
Player Ramos-Vinolas A. has played 170 matches
Player Raonic M. has played 290 matches
Player Reister J. has played 23 matches
Player Reynolds B. has played 6 matches
Player Riba P. has played 19 matches
Player Robert S. has played 68 matches
Player Robredo T. has played 193 matches
Player Rochus O. has played 6 matches
Player Roger-Vasselin E. has played 121 matches
Player Rola B. has played 25 matches
Player Rosol L. has played 188 matches
Player Rubin N. has played 12 matches
Player Rublev A. has played 58 matches
Player Rufin G. has played 22 matches
Player Russell M. has played 40 matches
Player Ruud C. has played 14 matches
Player Safwat M. has played 8 matches
Player Sakharov G. has played 2 matches
Player Sandgren T. has played 8 matches
Player Santillan A. has played 9 matches
Player Sarkissian A. has played 5 matches
Player Satral J. has played 3 matches
Player Saville L. has played 8 matches
Player Schwartzman D. has played 142 matches
Player Sela D. has played 115 matches
Player Seppi A. has played 231 matches
Player Shapovalov D. has played 21 matches
Player Sidorenko A. has played 3 matches
Player Sijsling I. has played 102 matches
Player Silva F.F. has played 2 matches
Player Simon G. has played 269 matches
Player Skugor F. has played 10 matches
Player Smith J.P. has played 20 matches
Player Smyczek T. has played 82 matches
Player Sock J. has played 233 matches
Player Soderlund C. has played 2 matches
Player Soeda G. has played 47 matches
Player Sorensen L. has played 2 matches
Player Sousa J. has played 256 matches
Player Sousa P. has played 4 matches
Player Souza J. has played 38 matches
Player Stakhovsky S. has played 137 matches
Player Starace P. has played 5 matches
Player Stebe C-M. has played 2 matches
Player Stebe C.M. has played 15 matches
Player Stepanek R. has played 106 matches
Player Struff J.L. has played 149 matches
Player Sugita Y. has played 65 matches
Player Thiem D. has played 269 matches
Player Thompson J. has played 40 matches
Player Tiafoe F. has played 38 matches
Player Tipsarevic J. has played 86 matches
Player Tomic B. has played 221 matches
Player Travaglia S. has played 5 matches
Player Trinker B. has played 3 matches
Player Troicki V. has played 219 matches
Player Trungelliti M. has played 11 matches
Player Tsitsipas S. has played 14 matches
Player Tsonga J.W. has played 249 matches
Player Tursunov D. has played 97 matches
Player Uchiyama Y. has played 5 matches
Player Ungur A. has played 14 matches
Player Vanni L. has played 21 matches
Player Venus M. has played 6 matches
Player Verdasco F. has played 256 matches
Player Vesely J. has played 175 matches
Player Viola M. has played 12 matches
Player Volandri F. has played 35 matches
Player Wang C. has played 2 matches
Player Wang J. has played 14 matches
Player Ward J. has played 35 matches
Player Wawrinka S. has played 300 matches
Player Weintraub A. has played 5 matches
Player Wessels L. has played 2 matches
Player Whittington A. has played 5 matches
Player Williams R. has played 23 matches
Player Willis M. has played 2 matches
Player Wu D. has played 17 matches
Player Ymer E. has played 30 matches
Player Ymer M. has played 8 matches
Player Young D. has played 173 matches
Player Youzhny M. has played 205 matches
Player Zeballos H. has played 121 matches
Player Zekic M. has played 3 matches
Player Zemlja G. has played 34 matches
Player Zhang Ze has played 10 matches
Player Zhang Zh. has played 5 matches
Player Zopp J. has played 17 matches
Player Zverev A. has played 183 matches
Player Zverev M. has played 111 matches

In [16]:
test_player = player_games[1]
pd.DataFrame(data=test_player[1]).head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41
0,2.0,Chennai,Chennai Open,41639.0,ATP250,Outdoor,Hard,1st Round,3.0,Granollers M.,Albot R.,222.0,169.0,215.0,311.0,6.0,4.0,3.0,6.0,6,0,,,,,2.0,1.0,Completed,1.28,3.50,1.30,3.40,1.29,3.5,1.37,3.34,1.29,3.25,1.37,4.70,1.31,3.36
1,27.0,Oeiras,Portugal Open,41758.0,ATP250,Outdoor,Clay,1st Round,3.0,Hanescu V.,Albot R.,93.0,178.0,601.0,298.0,3.0,6.0,6.0,4.0,6,4,,,,,2.0,1.0,Completed,1.22,4.00,1.22,4.00,1.25,3.75,1.24,4.55,1.22,4.00,1.25,4.90,1.22,4.10
2,38.0,Bastad,SkiStar Swedish Open,41828.0,ATP250,Outdoor,Clay,1st Round,3.0,Albot R.,De Schepper K.,229.0,110.0,212.0,541.0,7.0,6.0,6.0,1.0,,,,,,,2.0,0.0,Completed,2.10,1.66,2.20,1.65,2.2,1.62,2.33,1.67,2.10,1.73,2.35,1.73,2.18,1.66
3,38.0,Bastad,SkiStar Swedish Open,41830.0,ATP250,Outdoor,Clay,2nd Round,3.0,Berlocq C.,Albot R.,41.0,229.0,1010.0,212.0,5.0,7.0,6.0,4.0,6,2,,,,,2.0,1.0,Completed,1.10,7.00,1.13,5.50,1.12,5.5,1.11,8.04,1.13,6.00,1.15,8.04,1.11,6.29
4,51.0,New York,US Open,41877.0,Grand Slam,Outdoor,Hard,1st Round,5.0,Simon G.,Albot R.,31.0,201.0,1180.0,241.0,6.0,3.0,6.0,4.0,6,2,,,,,3.0,0.0,Completed,1.07,9.00,1.07,8.00,1.08,7,1.08,9.65,1.06,8.50,1.09,10.50,1.07,8.16

In [18]:
test_player[1].sort(key= lambda d:d[3], reverse=True)
pd.DataFrame(data=test_player[1]).head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41
0,55.0,St. Petersburg,St. Petersburg Open,42998.0,ATP250,Indoor,Hard,1st Round,3.0,Dutra Silva R.,Albot R.,399.0,108.0,105.0,510.0,2.0,6.0,6.0,2.0,6,2,,,,,2.0,1.0,Completed,2.50,1.50,2.40,1.50,,,2.76,1.50,2.76,1.58,2.59,1.51,NaN,NaN
1,53.0,New York,US Open,42979.0,Grand Slam,Outdoor,Hard,3rd Round,5.0,Querrey S.,Albot R.,21.0,138.0,2095.0,405.0,4.0,6.0,6.0,2.0,6,4,6,4,,,3.0,1.0,Completed,1.08,8.00,1.06,7.25,1.08,7.5,1.08,10.55,1.11,12.25,1.07,8.57,NaN,NaN
2,53.0,New York,US Open,42978.0,Grand Slam,Outdoor,Hard,2nd Round,5.0,Albot R.,Lu Y.H.,138.0,63.0,405.0,761.0,6.0,2.0,7.0,6.0,5,7,0,6,7,6,3.0,2.0,Completed,3.00,1.36,2.95,1.35,3,1.4,3.18,1.41,3.25,1.43,3.03,1.38,NaN,NaN
3,53.0,New York,US Open,42975.0,Grand Slam,Outdoor,Hard,1st Round,5.0,Albot R.,Escobedo E.,138.0,77.0,405.0,671.0,7.0,5.0,4.0,6.0,6,2,6,4,,,3.0,1.0,Completed,1.72,2.10,1.65,2.10,1.73,2.1,1.77,2.18,1.79,2.20,1.71,2.13,NaN,NaN
4,45.0,Gstaad,Suisse Open Gstaad,42942.0,ATP250,Outdoor,Clay,2nd Round,3.0,Goffin D.,Albot R.,13.0,132.0,2605.0,418.0,2.0,6.0,7.0,6.0,7,6,,,,,2.0,1.0,Completed,1.14,5.50,1.14,5.00,1.17,5,1.18,5.73,1.18,6.00,1.15,5.34,NaN,NaN

In [19]:
unique_locations = np.unique([data[i][1] for i in range(len(data))])
court_types = np.unique([data[i][5] for i in range(len(data))])
surface_types = np.unique([data[i][6] for i in range(len(data))])
tournament_round_types = np.unique([data[i][7] for i in range(len(data))])

print("{} unique locations".format(len(unique_locations)))
print("{} unique court types".format(len(court_types)))
print("{} unique surface types".format(len(surface_types)))
print("{} unique tournament round types".format(len(tournament_round_types)))
print("{} unique players".format(len(players)))

79 unique locations
2 unique court types
3 unique surface types
8 unique tournament round types
355 unique players

In [26]:
def process_player_data(games, name):
    # First sort the games:
    #games.sort(key=lambda game:game[3])
    
    x = []
    y = []
    
    for i, game in enumerate(games):
        p1_winner = game[9] == name
    
        location = np.float(one_hot(game[1], len(unique_locations), split="+")[0])
        #date = game[3]
        court = np.float(one_hot(game[5], len(court_types), split="+")[0])
        surface = np.float(one_hot(game[6], len(surface_types), split="+")[0])
        tournament_round = np.float(one_hot(game[7], len(tournament_round_types), split="+")[0])
        
        p1 = game[9] if p1_winner else game[10]
        p1 = np.float(one_hot(p1, len(players), split="+")[0])
        
        p2 = game[10] if p1_winner else game[9]
        p2 = np.float(one_hot(p2, len(players), split="+")[0])
        
        p1_rank = game[11] if p1_winner else game[12]
        if p1_rank == "N/A":
            continue
        
        p2_rank = game[12] if p1_winner else game[11]
        if p2_rank == "N/A":
            continue
            
        p1_bet = game[28] if p1_winner else game[29]
        p1_bet = p1_bet if (p1_bet != "") else 0.0
        p2_bet = game[29] if p1_winner else game[28]
        p2_bet = p2_bet if (p2_bet != "") else 0.0
        
        x.append([location, court, surface, tournament_round
                          , p1, p2, p1_rank, p2_rank])
        if p1_winner: y.append(0.0) 
        else: y.append(1.0)
        
    return x, y

In [27]:
for i in range(len(player_games)):
    bet = player_games[i][1][0][29]
    try:
        float(bet)
    except ValueError:
        print("Error with: ", bet)

Error with:
Error with:

In [28]:
x_data, y_data = [], []
for player in player_games:
    px, py = process_player_data(player[1], player[0])
    x_data += px
    y_data += py

print(len(x_data))
for a, b in zip(x_data[0:5], y_data[0:5]):
    print(b, " ",a)

25846
1.0   [47.0, 1.0, 2.0, 1.0, 32.0, 82.0, 834.0, 105.0]
0.0   [47.0, 1.0, 2.0, 1.0, 32.0, 42.0, 946.0, 45.0]
1.0   [47.0, 1.0, 2.0, 5.0, 32.0, 151.0, 946.0, 59.0]
1.0   [26.0, 1.0, 1.0, 1.0, 210.0, 77.0, 108.0, 399.0]
1.0   [8.0, 1.0, 1.0, 2.0, 210.0, 100.0, 138.0, 21.0]

In [29]:
input_dim = np.array(x_data[0]).shape
print(input_dim)

(8,)

In [31]:
model = Sequential()
model.add(Dense(64, activation="relu", input_dim=8))
model.add(Dense(64, activation="relu"))
model.add(Dense(64, activation="relu"))
model.add(Dropout(0.2))
model.add(Dense(64, activation="relu"))
model.add(Dense(1, activation="sigmoid"))

model.compile(optimizer="rmsprop", loss="binary_crossentropy", metrics=["accuracy"])

In [1]:
model.fit(x_data, y_data, batch_size=64, validation_split=0.2, epochs=100, shuffle=True)

NameError: name 'model' is not defined

In [2]:
def get_odds(games, winner):
    odds = []
    for game in games:
        
        p1_winner = game[9] == name
        
        p1_bet = game[28] if p1_winner else game[29]
        p1_bet = p1_bet if (p1_bet != "") else 0.0
        p2_bet = game[29] if p1_winner else game[28]
        p2_bet = p2_bet if (p2_bet != "") else 0.0
        odds.append([p1_bet, p2_bet])
        
    return odds

In [ ]:
odds = []
for player in player_games:
    o = get_odds(player[1], player[0])
    x_data += px
    y_data += py